# Generated by Django 4.1.1 on 2022-09-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team_1',
            new_name='liga',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_2',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ghost',
        ),
        migrations.RemoveField(
            model_name='game',
            name='point',
        ),
        migrations.AddField(
            model_name='team',
            name='ghost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='liga',
            name='date',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(max_length=254, upload_to='images'),
        ),
    ]
